
struct KeyArgumentMethod {
   
    /*========== CÁC THUỘC TÍNH CƠ BẢN CÀI ĐẶT CHUNG SDK ==========*/
   static let accessToken = "access_token"
   static let tokenId = "token_id"
   static let tokenKey = "token_key"
   static let versionSdk = "version_sdk"
   static let flowType = "flow_type"
   static let flowEKYC = "flow_ekyc"
   static let languageSdk = "language_sdk"
   static let challengeCode = "challenge_code"
   static let inputClientSession = "input_client_session"
   static let isShowTutorial = "is_show_tutorial"
   static let isDisableTutorial = "is_disable_tutorial"
   static let isShowRequiredPermissionDecree = "is_show_required_permission_decree"
   static let isEnableTutorialCardAdvance = "is_enable_tutorial_card_advance"
   static let modelHelpFace = "model_help_face"
   static let isEnableGotIt = "isEnableGotIt"
   static let isShowSwitchCamera = "is_show_switch_camera"
   static let cameraPositionForPortrait = "camera_position_for_portrait"
   static let zoomCamera = "zoomCamera"
   static let expiresTime = "expires_time"
   static let isTurnOffCallService = "is_turn_off_call_service"
   static let compressionQualityImage = "compression_quality_image"
   static let isEnableAutoBrightness = "is_enable_auto_brightness"
   static let screenBrightness = "screen_brightness"
   static let isSkipPreview = "is_skip_preview"
   static let isEnableEncrypt = "is_enable_encrypt"
   static let encryptPublicKey = "encrypt_public_key"
   static let modeUploadFile = "mode_upload_file"


/*========== CÁC THUỘC TÍNH VỀ GIẤY TỜ ==========*/   
    static let documentType = "document_type"
    static let hashFrontOCR = "hash_front_ocr"
    static let isCheckLivenessCard = "is_check_liveness_card"
    static let isEnableScanQRCode = "is_enable_scan_qrcode"
    static let isShowQRCodeResult = "is_show_qrcode_result"
    static let validateDocumentType = "validate_document_type"
    static let isValidatePostcode = "is_validate_postcode"
    static let listBlockedDocument = "list_blocked_document"
    static let modeVersionOCR = "mode_version_ocr"

    /*========== CÁC THUỘC TÍNH VỀ KHUÔN MẶT ==========*/   
 

    static let modeVersionFaceOval = "mode_version_face_oval"
    static let isEnableCompare = "is_enable_compare"
    static let compareType = "compare_type"
    static let hashImageCompare = "hash_image_compare"
    static let isCompareGeneral = "is_compare_general"
    static let thresLevel = "thres_level"
    static let checkLivenessFace = "check_liveness_face"
    static let isCheckMaskedFace = "is_check_masked_face"

    /*========== CÁC THUỘC TÍNH VỀ VIỆC QUAY VIDEO LẠI QUÁ TRÌNH THỰC HIỆN OCR VÀ FACE TRONG SDK ==========*/
    static let isRecordVideoFace = "is_record_video_face"
    static let isRecordVideoDocument = "is_record_video_document"
  

    /*========== CÁC THUỘC TÍNH VỀ MÔI TRƯỜNG PHÁT TRIỂN - URL TÁC VỤ TRONG SDK ==========*/
    static let isEnableWaterMark = "is_enable_water_mark"
    static let isAddMetadataImage = "is_add_metadata_image"
    static let timeoutCallApi = "timeout_call_api"
    static let changeBaseUrl = "change_base_url"
    static let urlUploadImage = "url_upload_image"
    static let urlOcr = "url_ocr"
    static let urlOcrFront = "url_ocr_front"
    static let urlCompare = "url_compare"
    static let urlCompareGeneral = "url_compare_general"
    static let urlVerifyFace = "url_verify_face"
    static let urlAddFace = "url_add_face"
    static let urlAddCardId = "url_add_card_id"
    static let urlLivenessCard = "url_liveness_card"
    static let urlCheckMaskedFace = "url_check_masked_face"
    static let urlSearchFace = "url_search_face"
    static let urlLivenessFace = "url_liveness_face"
    static let urlLivenessFace3D = "url_liveness_face3d"
    static let urlLogSdk = "url_log_sdk"
    static let headersRequest = "headers_request"
    static let transactionId = "transaction_id"
    static let transactionPartnerId = "transaction_partner_id"
    static let transactionPartnerIdOCR = "transaction_partner_id_ocr"
    static let transactionPartnerIdOCRFront = "transaction_partner_id_ocr_front"
    static let transactionPartnerIdLivenessFront = "transaction_partner_id_liveness_front"
    static let transactionPartnerIdLivenessBack = "transaction_partner_id_liveness_back"
    static let transactionPartnerIdCompareFace = "transaction_partner_id_compare_face"
    static let transactionPartnerIdLivenessFace = "transaction_partner_id_liveness_face"
    static let transactionPartnerIdMaskedFace = "transaction_partner_id_masked_face"
 



/*========== CHỈNH SỬA TÊN CÁC TỆP TIN HIỆU ỨNG - VIDEO HƯỚNG DẪN ==========*/
    static let nameOvalAnimation = "name_oval_animation"
    static let nameFeedbackAnimation = "name_feedback_animation"
    static let nameScanQRCodeAnimation = "name_scan_qrcode_animation"
    static let namePreviewDocumentAnimation = "name_preview_document_animation"
    static let nameLoadSuccessAnimation = "name_load_success_animation"
    static let nameHelpAudioFace = "name_help_audio_face"
    static let nameHelpVideoFace = "name_help_video_face"
    static let nameHelpVideoDocument = "name_help_video_document"

    /*========== CÁC THUỘC TÍNH VỀ MÀU SẮC GIAO DIỆN TRONG SDK ==========*/
    static let modeButtonHeaderBar = "mode_button_header_bar"
    static let contentColorHeaderBar = "content_color_header_bar"
    static let backgroundColorHeaderBar = "background_color_header_bar"
    static let textColorContentMain = "text_color_content_main"
    static let titleColorMain = "title_color_main"
    static let backgroundColorMainScreen = "background_color_main_screen"
    static let backgroundColorLine = "background_color_line"
    static let backgroundColorActiveButton = "background_color_active_button"
    static let backgroundColorDeactiveButton = "background_color_deactive_button"
    static let titleColorActiveButton = "title_color_active_button"
    static let titleColorDeactiveButton = "title_color_deactive_button"
    static let backgroundColorCaptureDocumentScreen = "background_color_capture_document_screen"
    static let backgroundColorCaptureFaceScreen = "background_color_capture_face_screen"
    static let effectColorNoticeFace = "effect_color_notice_face"
    static let textColorNoticeFace = "text_color_notice_face"
    static let effectColorNoticeInvalidFace = "effect_color_notice_invalid_face"
    static let colorContentFaceEffect = "color_content_face_effect"
    static let effectColorNoticeValidDocument = "effect_color_notice_valid_document"
    static let effectColorNoticeInvalidDocument = "effect_color_notice_invalid_document"
    static let textColorNoticeValidDocument = "text_color_notice_valid_document"
    static let textColorNoticeInvalidDocument = "text_color_notice_invalid_document"
    static let tintColorButtonCapture = "tint_color_button_capture"
    static let backgroundColorBorderCaptureFace = "background_color_border_capture_face"
    static let isShowLogo = "is_show_logo"
    static let logo = "logo"
    static let logoFaceOval = "logo_face_oval"
    static let widthLogo = "width_logo"
    static let heightLogo = "height_logo"
    static let imageTutorialQRCode = "image_tutorial_qrcode"
    static let imageTutorialFront = "image_tutorial_front"
    static let imageTutorialBack = "image_tutorial_back"
    static let imageTutorialBlur = "image_tutorial_blur"
    static let imageTutorialLostAngle = "image_tutorial_lost_angle"
    static let imageTutorialGlare = "image_tutorial_glare"
    static let backgroundColorPopup = "background_color_popup"
    static let textColorContentPopup = "text_color_content_popup"
    static let isEnableCheckVirtualCamera = "is_enable_check_virtual_camera"
    static let isEnableCheckSimulator = "is_enable_check_simulator"
    static let isEnableCheckJailbroken = "is_enable_check_jailbroken"
    static let isAnimatedDismissed = "is_animated_dismissed"
}


struct KeyResultConstantsNFC {
   static let cropParam = "CROP_PARAM"
   static let pathImageFrontFull = "PATH_IMAGE_FRONT_FULL"
   static let pathImageBackFull = "PATH_IMAGE_BACK_FULL"
   static let pathImageFaceFull = "PATH_IMAGE_FACE_FULL"
   static let pathImageFaceFarFull = "PATH_IMAGE_FACE_FAR_FULL"
   static let clientSessionResult = "CLIENT_SESSION_RESULT"
}
