package com.vnpt.flutter_plugin_ic_ekyc_lite

object KeyArgumentMethod {
    /*========== CÁC THUỘC TÍNH CƠ BẢN CÀI ĐẶT CHUNG SDK ==========*/
    const val ACCESS_TOKEN = "access_token"
    const val TOKEN_ID = "token_id"
    const val TOKEN_KEY = "token_key"
    const val VERSION_SDK = "version_sdk"
    const val FLOW_TYPE = "flow_type"
    const val FLOW_EKYC = "flow_ekyc"
    const val LANGUAGE_SDK = "language_sdk"
    const val CHALLENGE_CODE = "challenge_code"
    const val INPUT_CLIENT_SESSION = "input_client_session"
    const val IS_SHOW_TUTORIAL = "is_show_tutorial"
    const val IS_DISABLE_TUTORIAL = "is_disable_tutorial"
    const val IS_SHOW_REQUIRED_PERMISSION_DECREE = "is_show_required_permission_decree"
    const val IS_ENABLE_TUTORIAL_CARD_ADVANCE = "is_enable_tutorial_card_advance"
    const val MODEL_HELP_FACE = "model_help_face"
    const val IS_ENABLE_GOT_IT = "is_enable_gotit"
    const val IS_SHOW_SWITCH_CAMERA = "is_show_switch_camera"
    const val CAMERA_POSITION_FOR_PORTRAIT = "camera_position_for_portrait"
    const val ZOOM_CAMERA = "zoomCamera"
    const val EXPIRES_TIME = "expires_time"
    const val IS_TURN_OFF_CALL_SERVICE = "is_turn_off_call_service"
    const val COMPRESSION_QUALITY_IMAGE = "compression_quality_image"
    const val IS_ENABLE_AUTO_BRIGHTNESS = "is_enable_auto_brightness"
    const val SCREEN_BRIGHTNESS = "screen_brightness"
    const val IS_SKIP_PREVIEW = "is_skip_preview"
    const val IS_ENABLE_ENCRYPT = "is_enable_encrypt"
    const val ENCRYPT_PUBLIC_KEY = "encrypt_public_key"
    const val MODE_UPLOAD_FILE = "mode_upload_file"

    const val NUMBER_TIMES_RETRY_SCAN_QR_CODE = "number_times_retry_scan_qr_code"
    const val TIMEOUT_QR_CODE_FLOW = "timeout_qr_code_flow"

    /*========== CÁC THUỘC TÍNH VỀ GIẤY TỜ ==========*/
    const val DOCUMENT_TYPE = "document_type"
    const val HASH_FRONT_OCR = "hash_front_ocr"
    const val IS_CHECK_LIVENESS_CARD = "is_check_liveness_card"
    const val IS_ENABLE_SCAN_QR_CODE = "is_enable_scan_qrcode"
    const val IS_SHOW_QR_CODE_RESULT = "is_show_qrcode_result"
    const val VALIDATE_DOCUMENT_TYPE = "validate_document_type"
    const val IS_VALIDATE_POSTCODE = "is_validate_postcode"
    const val LIST_BLOCKED_DOCUMENT = "list_blocked_document"
    const val MODE_VERSION_OCR = "mode_version_ocr"

    /*========== CÁC THUỘC TÍNH VỀ KHUÔN MẶT ==========*/
    const val MODE_VERSION_FACE_OVAL = "mode_version_face_oval"
    const val IS_ENABLE_COMPARE = "is_enable_compare"
    const val COMPARE_TYPE = "compare_type"
    const val HASH_IMAGE_COMPARE = "hash_image_compare"
    const val IS_COMPARE_GENERAL = "is_compare_general"
    const val THRES_LEVEL = "thres_level"
    const val CHECK_LIVENESS_FACE = "check_liveness_face"
    const val IS_CHECK_MASKED_FACE = "is_check_masked_face"

    /*========== CÁC THUỘC TÍNH VỀ VIỆC QUAY VIDEO LẠI QUÁ TRÌNH THỰC HIỆN OCR VÀ FACE TRONG SDK ==========*/
    const val IS_RECORD_VIDEO_FACE = "is_record_video_face"
    const val IS_RECORD_VIDEO_DOCUMENT = "is_record_video_document"


    /*========== CÁC THUỘC TÍNH VỀ MÔI TRƯỜNG PHÁT TRIỂN - URL TÁC VỤ TRONG SDK ==========*/
    const val IS_ENABLE_WATER_MARK = "is_enable_water_mark"
    const val IS_ADD_METADATA_IMAGE = "is_add_metadata_image"
    const val TIMEOUT_CALL_API = "timeout_call_api"
    const val CHANGE_BASE_URL = "change_base_url"
    const val URL_UPLOAD_IMAGE = "url_upload_image"
    const val URL_OCR = "url_ocr"
    const val URL_OCR_FRONT = "url_ocr_front"
    const val URL_COMPARE = "url_compare"
    const val URL_COMPARE_GENERAL = "url_compare_general"
    const val URL_VERIFY_FACE = "url_verify_face"
    const val URL_ADD_FACE = "url_add_face"
    const val URL_ADD_CARD_ID = "url_add_card_id"
    const val URL_LIVENESS_CARD = "url_liveness_card"
    const val URL_CHECK_MASKED_FACE = "url_check_masked_face"
    const val URL_SEARCH_FACE = "url_search_face"
    const val URL_LIVENESS_FACE = "url_liveness_face"
    const val URL_LIVENESS_FACE_3D = "url_liveness_face3d"
    const val URL_LOG_SDK = "url_log_sdk"
    const val HEADERS_REQUEST = "headers_request"
    const val TRANSACTION_ID = "transaction_id"
    const val TRANSACTION_PARTNER_ID = "transaction_partner_id"
    const val TRANSACTION_PARTNER_ID_OCR = "transaction_partner_id_ocr"
    const val TRANSACTION_PARTNER_ID_OCR_FRONT = "transaction_partner_id_ocr_front"
    const val TRANSACTION_PARTNER_ID_LIVENESS_FRONT = "transaction_partner_id_liveness_front"
    const val TRANSACTION_PARTNER_ID_LIVENESS_BACK = "transaction_partner_id_liveness_back"
    const val TRANSACTION_PARTNER_ID_COMPARE_FACE = "transaction_partner_id_compare_face"
    const val TRANSACTION_PARTNER_ID_LIVENESS_FACE = "transaction_partner_id_liveness_face"
    const val TRANSACTION_PARTNER_ID_MASKED_FACE = "transaction_partner_id_masked_face"

    /*========== CHỈNH SỬA TÊN CÁC TỆP TIN HIỆU ỨNG - VIDEO HƯỚNG DẪN ==========*/
    const val NAME_OVAL_ANIMATION = "name_oval_animation"
    const val NAME_FEEDBACK_ANIMATION = "name_feedback_animation"
    const val NAME_SCAN_QR_CODE_ANIMATION = "name_scan_qrcode_animation"
    const val NAME_PREVIEW_DOCUMENT_ANIMATION = "name_preview_document_animation"
    const val NAME_LOAD_SUCCESS_ANIMATION = "name_load_success_animation"
    const val NAME_HELP_AUDIO_FACE = "name_help_audio_face"
    const val NAME_HELP_VIDEO_FACE = "name_help_video_face"
    const val NAME_HELP_VIDEO_DOCUMENT = "name_help_video_document"

    /*========== CÁC THUỘC TÍNH VỀ MÀU SẮC GIAO DIỆN TRONG SDK ==========*/
    const val MODE_BUTTON_HEADER_BAR = "mode_button_header_bar"
    const val CONTENT_COLOR_HEADER_BAR = "content_color_header_bar"
    const val BACKGROUND_COLOR_HEADER_BAR = "background_color_header_bar"
    const val TEXT_COLOR_CONTENT_MAIN = "text_color_content_main"
    const val TITLE_COLOR_MAIN = "title_color_main"
    const val BACKGROUND_COLOR_MAIN_SCREEN = "background_color_main_screen"
    const val BACKGROUND_COLOR_LINE = "background_color_line"
    const val BACKGROUND_COLOR_ACTIVE_BUTTON = "background_color_active_button"
    const val BACKGROUND_COLOR_DEACTIVE_BUTTON = "background_color_deactive_button"
    const val TITLE_COLOR_ACTIVE_BUTTON = "title_color_active_button"
    const val TITLE_COLOR_DEACTIVE_BUTTON = "title_color_deactive_button"
    const val BACKGROUND_COLOR_CAPTURE_DOCUMENT_SCREEN = "background_color_capture_document_screen"
    const val BACKGROUND_COLOR_CAPTURE_FACE_SCREEN = "background_color_capture_face_screen"
    const val EFFECT_COLOR_NOTICE_FACE = "effect_color_notice_face"
    const val TEXT_COLOR_NOTICE_FACE = "text_color_notice_face"
    const val EFFECT_COLOR_NOTICE_INVALID_FACE = "effect_color_notice_invalid_face"
    const val COLOR_CONTENT_FACE_EFFECT = "color_content_face_effect"
    const val EFFECT_COLOR_NOTICE_VALID_DOCUMENT = "effect_color_notice_valid_document"
    const val EFFECT_COLOR_NOTICE_INVALID_DOCUMENT = "effect_color_notice_invalid_document"
    const val TEXT_COLOR_NOTICE_VALID_DOCUMENT = "text_color_notice_valid_document"
    const val TEXT_COLOR_NOTICE_INVALID_DOCUMENT = "text_color_notice_invalid_document"
    const val TINT_COLOR_BUTTON_CAPTURE = "tint_color_button_capture"
    const val BACKGROUND_COLOR_BORDER_CAPTURE_FACE = "background_color_border_capture_face"
    const val IS_SHOW_LOGO = "is_show_logo"
    const val LOGO = "logo"
    const val LOGO_FACE_OVAL = "logo_face_oval"
    const val WIDTH_LOGO = "width_logo"
    const val HEIGHT_LOGO = "height_logo"
    const val IMAGE_TUTORIAL_QR_CODE = "image_tutorial_qrcode"
    const val IMAGE_TUTORIAL_FRONT = "image_tutorial_front"
    const val IMAGE_TUTORIAL_BACK = "image_tutorial_back"
    const val IMAGE_TUTORIAL_BLUR = "image_tutorial_blur"
    const val IMAGE_TUTORIAL_LOST_ANGLE = "image_tutorial_lost_angle"
    const val IMAGE_TUTORIAL_GLARE = "image_tutorial_glare"
    const val BACKGROUND_COLOR_POPUP = "background_color_popup"
    const val TEXT_COLOR_CONTENT_POPUP = "text_color_content_popup"
    const val IS_ENABLE_CHECK_VIRTUAL_CAMERA = "is_enable_check_virtual_camera"
    const val IS_ENABLE_CHECK_SIMULATOR = "is_enable_check_simulator"
    const val IS_ENABLE_CHECK_JAILBROKEN = "is_enable_check_jailbroken"
    const val IS_ANIMATED_DISMISSED = "is_animated_dismissed"
}


object KeyResultConstantsEKYC {
    const val CROP_PARAM = "CROP_PARAM"
    const val PATH_IMAGE_FRONT_FULL = "PATH_IMAGE_FRONT_FULL"
    const val PATH_IMAGE_BACK_FULL = "PATH_IMAGE_BACK_FULL"
    const val PATH_IMAGE_FACE_FULL = "PATH_IMAGE_FACE_FULL"
    const val PATH_IMAGE_FACE_FAR_FULL = "PATH_IMAGE_FACE_FAR_FULL"
    const val PATH_IMAGE_FACE_NEAR_FULL = "PATH_IMAGE_FACE_NEAR_FULL"
    const val PATH_IMAGE_FACE_SCAN_3D = "PATH_FACE_SCAN3D"
    const val CLIENT_SESSION_RESULT = "CLIENT_SESSION_RESULT"

    // QR Code results
    const val QR_CODE_RESULT = "QR_CODE_RESULT"
    const val PATH_IMAGE_QR_CODE_FULL = "PATH_IMAGE_QR_CODE_FULL"
    const val QR_CODE_RESULT_DETAIL = "QR_CODE_RESULT_DETAIL"
    const val RETRY_QR_CODE_RESULT = "RETRY_QR_CODE_RESULT"
    
}